### ISSUE TITLE
Creating an "i" indexed table from another [i][1] indexed table is not allowed

### ISSUE THREAD

**Issue by SeraphL** [dimitrijejankov/simsql#2]
For example, the following query reports an error:

create table a[i](dataID, dldv) as
    select e1.dataID, e1.dldv
    from b[i][1] as e1;

The general index does not have index "i" !
Error parsing query:Nothing came back from the type checker!

**Comment by dimitrijejankov** [comment]
The bug was caused by the fact that the general index table definition didn't allow constant indexes, with the new table dependency graph generation this shouldn't be an issue. The solution was to remove the check from the typechecker.
